name: Issue or feature request related to the GUI
description: Any report, issue or feature request related to the GUI
labels: [GUI]
body:
- type: markdown
  attributes:
    value: |
      Use this template for BitStar Core GUI issues or GUI feature requests.

- type: checkboxes
  id: acknowledgement
  attributes:
    label: This issue is related to the BitStar Core GUI
    description: If this is a release verification result, use the independent verification report template instead.
    options:
      - label: I still think this issue should be opened here
        required: true
- type: textarea
  id: gui-request
  attributes:
    label: Report
  validations:
    required: true
